# Generated by Django 3.2.22 on 2023-10-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='influencer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('insight', models.IntegerField(blank=True, null=True)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
