# Generated by Django 3.2.22 on 2023-10-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araapp', '0002_auto_20231019_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencer_info',
            options={'managed': False},
        ),
    ]
