# Generated by Django 3.2.22 on 2023-10-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araapp', '0003_alter_influencer_info_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='influencer_info',
            table='influencer_info',
        ),
    ]
