# Generated by Django 3.2.22 on 2023-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araapp', '0004_alter_influencer_info_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='influencer_cate_region_bscore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('insta_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cate1', models.CharField(blank=True, max_length=100, null=True)),
                ('cate2', models.CharField(blank=True, max_length=100, null=True)),
                ('cate3', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commer_power', models.CharField(blank=True, max_length=100, null=True)),
                ('influ_power', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'influencer_cate_region_bscore',
                'managed': False,
            },
        ),
    ]
